#!/usr/bin/env bash


for i in $(git submodule foreach --quiet 'echo $path')
do
  (cd $i
#   echo ".npmignore" >> .npmignore
#   git add .npmignore
#   git commit -m 'chore(npm): ignore .npmignore'
#   git push
  )
done

